kind: Secret
apiVersion: v1
metadata:
  namespace: {{ .Release.Namespace }}
  name: "{{ .Values.service.name }}-acr-secret"
  labels:
    build: "{{ .Values.service.build }}"
data:
  .dockerconfigjson: "{{ .Values.service.containerRegistrySecret }}"
type: kubernetes.io/dockerconfigjson