apiVersion: v1
kind: Service
metadata:
  namespace: "{{ .Release.Namespace }}"
  name: "{{ .Values.service.name }}-db-ip"
spec:
  selector:
    app: "{{ .Values.service.name }}-db"
  type: ClusterIP
  ports:
    - port: 8123
      targetPort: 8123