apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: "{{ .Values.service.name }}-ui-loadbalancer"
  labels:
    build: "{{ .Values.service.build }}"
spec:
  selector:
    app: "{{ .Values.service.name }}-ui"
  type: LoadBalancer
  ports:
    - port: 443
      targetPort: 443